<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>pd_analise_exploratoria_dados</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="pd_analise_exploratoria_dados_files/libs/clipboard/clipboard.min.js"></script>
<script src="pd_analise_exploratoria_dados_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="pd_analise_exploratoria_dados_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="pd_analise_exploratoria_dados_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="pd_analise_exploratoria_dados_files/libs/quarto-html/popper.min.js"></script>
<script src="pd_analise_exploratoria_dados_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="pd_analise_exploratoria_dados_files/libs/quarto-html/anchor.min.js"></script>
<link href="pd_analise_exploratoria_dados_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="pd_analise_exploratoria_dados_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="pd_analise_exploratoria_dados_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="pd_analise_exploratoria_dados_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="pd_analise_exploratoria_dados_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">pd_analise_exploratoria_dados</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introdução-e-escolha-da-base-de-dados" class="level1">
<h1>1. Introdução e Escolha da Base de Dados</h1>
<p>A base de dados utilizada neste trabalho tem origem no dataset Life Expectancy (WHO) - 2025, obtido no <a href="https://www.kaggle.com/datasets/khunglongg/life-expectancy-who-2025">Kaggle</a>, baseado em um relatório publicado pela própria <strong>World Health Organization (WHO)</strong></p>
<p><img src="images/relatorio_who.png" class="img-fluid"></p>
<p>Motivo da Escolha: Fiz questão de, neste trabalho, buscar uma base de dados real e que nos permitisse insights interessantes e relevantes para a atualidade. Experiências anteriores com bases sintéticas mostraram que nem sempre é possível este tipo de análise quando os dados não são reais. Desta forma, este dataset foi selecionado por apresentar uma estrutura rica para análise, atendendo os requisitos do projeto por possuir mais de 4 variáveis numéricas de interesse e presença de dados faltantes, permitindo a prática de técnicas de imputação.</p>
<p>Resultados Esperados: Espera-se identificar quais fatores possuem maior correlação com a expectativa de vida e verificar como essas variáveis se distribuem através dos países, além de tratar as lacunas nos dados para garantir uma análise robusta. A análise visa fornecer insights sobre os determinantes da expectativa de vida.</p>
</section>
<section id="importação-das-bibliotecas-e-preparação-dos-dados" class="level1">
<h1>2. Importação das bibliotecas e preparação dos dados</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregamento de bibliotecas</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)   </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'summarytools'

O seguinte objeto é mascarado por 'package:tibble':

    view</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)       </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)         </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'lme4':
  method           from
  na.action.merMod car 

Anexando pacote: 'mice'

O seguinte objeto é mascarado por 'package:stats':

    filter

Os seguintes objetos são mascarados por 'package:base':

    cbind, rbind</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)    </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)    </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.95 loaded</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Leitura dos dados do arquivo CSV </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/Life_expectancy_2025.csv"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Padronizando nomes de colunas (substituindo espaços por underscores)</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df) <span class="ot">&lt;-</span> <span class="fu">make.names</span>(<span class="fu">names</span>(df))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   193 obs. of  22 variables:
 $ Country                        : chr  "Afghanistan" "Albania" "Algeria" "Angola" ...
 $ Status                         : chr  "Developing" "Developing" "Developing" "Developing" ...
 $ Year                           : int  2025 2025 2025 2025 2025 2025 2025 2025 2025 2025 ...
 $ Life.expectancy                : num  58.2 75.2 73.6 49 75.1 ...
 $ Adult.Mortality                : num  269.1 45.1 108.2 328.6 127.5 ...
 $ infant.deaths                  : num  78.25 0.688 20.312 83.75 0 ...
 $ Alcohol                        : num  0.0144 4.8487 0.4067 5.7407 7.9493 ...
 $ percentage.expenditure         : num  35 193 236 102 1002 ...
 $ Hepatitis.B                    : num  64.6 98 78 70.2 98.3 ...
 $ Measles                        : num  2362.2 53.4 1943.9 3561.3 0 ...
 $ BMI                            : num  15.5 49.1 48.7 18 38.4 ...
 $ under.five.deaths              : num  107.562 0.938 23.5 132.625 0 ...
 $ Polio                          : num  48.4 98.1 91.8 46.1 96.9 ...
 $ Total.expenditure              : num  8.25 5.95 4.6 3.92 4.79 ...
 $ Diphtheria                     : num  52.3 98.1 91.9 47.7 98.3 ...
 $ HIV.AIDS                       : num  0.1 0.1 0.1 2.369 0.125 ...
 $ GDP                            : num  340 2120 2848 1975 9759 ...
 $ Population                     : num  33831764 696912 21649827 10147099 91818 ...
 $ thinness.1.19.years            : num  16.58 1.62 6.09 6.19 3.42 ...
 $ thinness.5.9.years             : num  15.58 1.7 5.97 6.67 3.38 ...
 $ Income.composition.of.resources: num  0.415 0.71 0.695 0.458 0.489 ...
 $ Schooling                      : num  8.21 12.14 12.71 8.04 8.84 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Country             Status               Year      Life.expectancy
 Length:193         Length:193         Min.   :2025   Min.   :46.11  
 Class :character   Class :character   1st Qu.:2025   1st Qu.:62.48  
 Mode  :character   Mode  :character   Median :2025   Median :72.49  
                                       Mean   :2025   Mean   :69.22  
                                       3rd Qu.:2025   3rd Qu.:75.11  
                                       Max.   :2025   Max.   :82.54  
                                                      NA's   :10     
 Adult.Mortality  infant.deaths         Alcohol        percentage.expenditure
 Min.   : 18.75   Min.   :   0.000   Min.   : 0.0100   Min.   :   0.00       
 1st Qu.: 80.41   1st Qu.:   0.000   1st Qu.: 0.9697   1st Qu.:  26.12       
 Median :146.56   Median :   2.562   Median : 3.5053   Median : 139.16       
 Mean   :164.80   Mean   :  28.832   Mean   : 4.4399   Mean   : 708.81       
 3rd Qu.:219.59   3rd Qu.:  20.750   3rd Qu.: 7.4430   3rd Qu.: 508.49       
 Max.   :550.06   Max.   :1366.688   Max.   :13.4973   Max.   :9801.81       
 NA's   :10                          NA's   :2                               
  Hepatitis.B       Measles               BMI        under.five.deaths
 Min.   : 8.00   Min.   :    0.000   Min.   : 5.20   Min.   :   0.00  
 1st Qu.:67.45   1st Qu.:    3.312   1st Qu.:20.93   1st Qu.:   0.00  
 Median :83.23   Median :  130.625   Median :43.91   Median :   3.25  
 Mean   :78.52   Mean   : 2302.060   Mean   :39.55   Mean   :  39.99  
 3rd Qu.:94.56   3rd Qu.: 1497.188   3rd Qu.:52.36   3rd Qu.:  24.88  
 Max.   :99.00   Max.   :65857.938   Max.   :87.30   Max.   :1812.50  
 NA's   :9                           NA's   :4                        
     Polio       Total.expenditure   Diphtheria       HIV.AIDS      
 Min.   : 9.00   Min.   : 1.647    Min.   : 9.00   Min.   : 0.1000  
 1st Qu.:71.75   1st Qu.: 4.675    1st Qu.:72.38   1st Qu.: 0.1000  
 Median :88.00   Median : 5.962    Median :88.19   Median : 0.1000  
 Mean   :82.43   Mean   : 6.028    Mean   :82.23   Mean   : 1.6623  
 3rd Qu.:96.00   3rd Qu.: 7.080    3rd Qu.:96.00   3rd Qu.: 0.8187  
 Max.   :99.00   Max.   :17.240    Max.   :99.00   Max.   :32.9438  
                 NA's   :2                                          
      GDP            Population        thinness.1.19.years thinness.5.9.years
 Min.   :  136.2   Min.   :      292   Min.   : 0.100      Min.   : 0.100    
 1st Qu.:  868.0   1st Qu.:   660051   1st Qu.: 1.619      1st Qu.: 1.562    
 Median : 3042.6   Median :  3743167   Median : 3.444      Median : 3.487    
 Mean   : 7761.7   Mean   : 14913268   Mean   : 4.683      Mean   : 4.711    
 3rd Qu.: 7927.1   3rd Qu.: 11370431   3rd Qu.: 7.106      3rd Qu.: 6.987    
 Max.   :57362.9   Max.   :421467691   Max.   :27.100      Max.   :27.944    
 NA's   :10        NA's   :1           NA's   :4           NA's   :4         
 Income.composition.of.resources   Schooling     
 Min.   :0.1317                  Min.   : 0.000  
 1st Qu.:0.4809                  1st Qu.: 9.944  
 Median :0.6612                  Median :12.334  
 Mean   :0.6295                  Mean   :11.894  
 3rd Qu.:0.7634                  3rd Qu.:14.069  
 Max.   :0.9314                  Max.   :20.038  
 NA's   :17                      NA's   :13      </code></pre>
</div>
</div>
<p>Em especial, pretendo focar em variáveis estruturais gerais, e não diretamente relacionadas à “tempo de vida”, desta forma, variáveis como infant.deaths, adult.mortality, thinness.1.19.years e as doenças individualmente não vão ser analisádas neste relatório.</p>
</section>
<section id="análise-univariada-descrição-estatística" class="level1">
<h1>3. Análise Univariada: Descrição Estatística</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecionando variáveis de interesse para a análise</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>vars_interesse <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    Life.expectancy,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    Alcohol,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    percentage.expenditure,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    BMI,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    Total.expenditure,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    GDP,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    Population,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    Income.composition.of.resources,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    Schooling</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Descrição estatística usando summarytools::descr</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="fu">descr</span>(vars_interesse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Descriptive Statistics  
vars_interesse  
N: 193  

                    Alcohol      BMI        GDP   Income.composition.of.resources   Life.expectancy
----------------- --------- -------- ---------- --------------------------------- -----------------
             Mean      4.44    39.55    7761.75                              0.63             69.22
          Std.Dev      3.88    17.60   11379.52                              0.18              9.19
              Min      0.01     5.20     136.18                              0.13             46.11
               Q1      0.95    20.92     837.92                              0.48             62.38
           Median      3.51    43.91    3042.60                              0.66             72.49
               Q3      7.47    52.36    7951.82                              0.76             75.16
              Max     13.50    87.30   57362.87                              0.93             82.54
              MAD      4.43    17.67    3569.44                              0.21              8.90
              IQR      6.47    31.43    7059.16                              0.28             12.63
               CV      0.87     0.45       1.47                              0.29              0.13
         Skewness      0.59     0.10       2.22                             -0.44             -0.58
      SE.Skewness      0.18     0.18       0.18                              0.18              0.18
         Kurtosis     -0.90    -0.74       4.83                             -0.64             -0.64
          N.Valid    191.00   189.00     183.00                            176.00            183.00
                N    193.00   193.00     193.00                            193.00            193.00
        Pct.Valid     98.96    97.93      94.82                             91.19             94.82

Table: Table continues below

 

                    percentage.expenditure     Population   Schooling   Total.expenditure
----------------- ------------------------ -------------- ----------- -------------------
             Mean                   708.81    14913267.79       11.89                6.03
          Std.Dev                  1449.45    41750148.38        3.34                2.21
              Min                     0.00         292.00        0.00                1.65
               Q1                    26.12      656769.00        9.93                4.67
           Median                   139.16     3743166.84       12.33                5.96
               Q3                   508.49    11376807.91       14.08                7.09
              Max                  9801.81   421467690.94       20.04               17.24
              MAD                   206.31     5067139.42        3.01                1.85
              IQR                   482.37    10710379.92        4.12                2.41
               CV                     2.04           2.80        0.28                0.37
         Skewness                     3.26           7.08       -0.67                1.62
      SE.Skewness                     0.17           0.18        0.18                0.18
         Kurtosis                    12.28          59.27        1.11                6.31
          N.Valid                   193.00         192.00      180.00              191.00
                N                   193.00         193.00      193.00              193.00
        Pct.Valid                   100.00          99.48       93.26               98.96</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabela descritiva formatada</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_summary</span>(vars_interesse) <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_n</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modify_header</span>(<span class="at">label =</span> <span class="st">"**Variável**"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modify_spanning_header</span>(<span class="fu">c</span>(stat_0) <span class="sc">~</span> <span class="st">"**Estatísticas Descritivas**"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="vjakglmqwi" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#vjakglmqwi table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#vjakglmqwi thead, #vjakglmqwi tbody, #vjakglmqwi tfoot, #vjakglmqwi tr, #vjakglmqwi td, #vjakglmqwi th {
  border-style: none;
}

#vjakglmqwi p {
  margin: 0;
  padding: 0;
}

#vjakglmqwi .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#vjakglmqwi .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#vjakglmqwi .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#vjakglmqwi .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#vjakglmqwi .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vjakglmqwi .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vjakglmqwi .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vjakglmqwi .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#vjakglmqwi .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#vjakglmqwi .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#vjakglmqwi .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#vjakglmqwi .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#vjakglmqwi .gt_spanner_row {
  border-bottom-style: hidden;
}

#vjakglmqwi .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#vjakglmqwi .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#vjakglmqwi .gt_from_md > :first-child {
  margin-top: 0;
}

#vjakglmqwi .gt_from_md > :last-child {
  margin-bottom: 0;
}

#vjakglmqwi .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#vjakglmqwi .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#vjakglmqwi .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#vjakglmqwi .gt_row_group_first td {
  border-top-width: 2px;
}

#vjakglmqwi .gt_row_group_first th {
  border-top-width: 2px;
}

#vjakglmqwi .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vjakglmqwi .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#vjakglmqwi .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#vjakglmqwi .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vjakglmqwi .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vjakglmqwi .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#vjakglmqwi .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#vjakglmqwi .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#vjakglmqwi .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vjakglmqwi .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vjakglmqwi .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vjakglmqwi .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vjakglmqwi .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vjakglmqwi .gt_left {
  text-align: left;
}

#vjakglmqwi .gt_center {
  text-align: center;
}

#vjakglmqwi .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#vjakglmqwi .gt_font_normal {
  font-weight: normal;
}

#vjakglmqwi .gt_font_bold {
  font-weight: bold;
}

#vjakglmqwi .gt_font_italic {
  font-style: italic;
}

#vjakglmqwi .gt_super {
  font-size: 65%;
}

#vjakglmqwi .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#vjakglmqwi .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#vjakglmqwi .gt_indent_1 {
  text-indent: 5px;
}

#vjakglmqwi .gt_indent_2 {
  text-indent: 10px;
}

#vjakglmqwi .gt_indent_3 {
  text-indent: 15px;
}

#vjakglmqwi .gt_indent_4 {
  text-indent: 20px;
}

#vjakglmqwi .gt_indent_5 {
  text-indent: 25px;
}

#vjakglmqwi .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#vjakglmqwi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Variável</strong></th>
<th rowspan="2" id="n" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>N</strong></th>
<th id="level 1; stat_0" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="col"><div class="gt_column_spanner">
<strong>Estatísticas Descritivas</strong>
</div></th>
</tr>
<tr class="gt_col_headings even">
<th id="stat_0" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>N = 193</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">Life.expectancy</td>
<td class="gt_row gt_center" headers="n">183</td>
<td class="gt_row gt_center" headers="stat_0">72 (62, 75)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_0">10</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">Alcohol</td>
<td class="gt_row gt_center" headers="n">191</td>
<td class="gt_row gt_center" headers="stat_0">3.5 (0.9, 7.5)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_0">2</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">percentage.expenditure</td>
<td class="gt_row gt_center" headers="n">193</td>
<td class="gt_row gt_center" headers="stat_0">139 (26, 508)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">BMI</td>
<td class="gt_row gt_center" headers="n">189</td>
<td class="gt_row gt_center" headers="stat_0">44 (21, 52)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_0">4</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">Total.expenditure</td>
<td class="gt_row gt_center" headers="n">191</td>
<td class="gt_row gt_center" headers="stat_0">5.96 (4.67, 7.09)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_0">2</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">GDP</td>
<td class="gt_row gt_center" headers="n">183</td>
<td class="gt_row gt_center" headers="stat_0">3,043 (838, 7,952)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_0">10</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">Population</td>
<td class="gt_row gt_center" headers="n">192</td>
<td class="gt_row gt_center" headers="stat_0">3,743,167 (656,769, 11,376,808)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_0">1</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">Income.composition.of.resources</td>
<td class="gt_row gt_center" headers="n">176</td>
<td class="gt_row gt_center" headers="stat_0">0.66 (0.48, 0.76)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_0">17</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">Schooling</td>
<td class="gt_row gt_center" headers="n">180</td>
<td class="gt_row gt_center" headers="stat_0">12.3 (9.9, 14.1)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center" headers="n"><br>
</td>
<td class="gt_row gt_center" headers="stat_0">13</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="3" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Median (Q1, Q3)</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p>A partir destes dados podemos que a nossa base é altamente heterogênea, com a expectativa de vida variando de 46 até 82 anos (com desvio padrão de 9). Outra variável que chama especialmente a atenção é o GDP (PIB), que vai desde 136 até 57362, possuindo uma média de 7761 e desvio padrão de 11375. População também possui variações bastante significativas como essas.</p>
</section>
<section id="análise-bivariada-correlação-e-matriz-de-espalhamento" class="level1">
<h1>4. Análise Bivariada: Correlação e Matriz de Espalhamento</h1>
<p>Com esta análise buscamos observar a relação entre pares de variáveis, para identificar padrões de correlações no nosso dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Criando a matriz de espalhamento para as variáveis de interesse</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  vars_interesse,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Matriz de Espalhamento das Variáveis de Interesse"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">35</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">0.1</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.25</span>),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex.labels =</span> <span class="fl">0.8</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower.panel =</span> panel.smooth</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculando a matriz de correlação</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(vars_interesse, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(cor_matrix, <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                Life.expectancy Alcohol percentage.expenditure
Life.expectancy                            1.00    0.46                   0.52
Alcohol                                    0.46    1.00                   0.47
percentage.expenditure                     0.52    0.47                   1.00
BMI                                        0.72    0.30                   0.30
Total.expenditure                          0.29    0.30                   0.19
GDP                                        0.60    0.52                   0.80
Population                                -0.01   -0.02                  -0.08
Income.composition.of.resources            0.82    0.55                   0.57
Schooling                                  0.79    0.61                   0.52
                                  BMI Total.expenditure  GDP Population
Life.expectancy                  0.72              0.29 0.60      -0.01
Alcohol                          0.30              0.30 0.52      -0.02
percentage.expenditure           0.30              0.19 0.80      -0.08
BMI                              1.00              0.42 0.38      -0.11
Total.expenditure                0.42              1.00 0.26       0.06
GDP                              0.38              0.26 1.00       0.12
Population                      -0.11              0.06 0.12       1.00
Income.composition.of.resources  0.66              0.27 0.65      -0.02
Schooling                        0.49              0.09 0.57      -0.05
                                Income.composition.of.resources Schooling
Life.expectancy                                            0.82      0.79
Alcohol                                                    0.55      0.61
percentage.expenditure                                     0.57      0.52
BMI                                                        0.66      0.49
Total.expenditure                                          0.27      0.09
GDP                                                        0.65      0.57
Population                                                -0.02     -0.05
Income.composition.of.resources                            1.00      0.86
Schooling                                                  0.86      1.00</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizando a matriz de correlação com corrplot</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  cor_matrix,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"color"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"upper"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.col =</span> <span class="st">"black"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.srt =</span> <span class="dv">45</span>,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.cex =</span> <span class="fl">0.7</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">addCoef.col =</span> <span class="st">"black"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">number.cex =</span> <span class="fl">0.5</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Apesar do número de variáveis dificultar um pouco a avaliação visual da matriz de espalhamento, é possível identificar que algumas variáveis apresentam associação positiva mais forte com a expectativa de vida. Os casos mais evidentes são BMI, Income.composition.of.resources e Schooling, que também aparecem com os maiores coeficientes de correlação positiva na matriz de correlação. Em especial, Income.composition.of.resources e Schooling se destacam por apresentarem relações quase lineares com a expectativa de vida. Já variáveis como GDP e percentage.expenditure também apresentam correlação positiva moderada, mas, pela matriz de espalhamento, essa relação parece menos uniforme e mais influenciada pelos países com valores mais elevados. Por outro lado, Population praticamente não apresenta associação com a expectativa de vida, enquanto Total.expenditure mostra apenas uma relação fraca. Assim, os resultados sugerem que fatores ligados ao desenvolvimento humano e à educação parecem estar mais fortemente associados à expectativa de vida do que variáveis econômicas isoladas ou o tamanho da população.</p>
</section>
<section id="normalidade-das-variáveis" class="level1">
<h1>5. Normalidade das Variáveis</h1>
<p>Nesta etapa analisaremos a distribuição individual de cada variável, com o objetivo de verificar se elas apresentam comportamento próximo de uma distribuição normal. A distribuição normal, também chamada de Gaussiana, é uma distribuição contínua e simétrica em torno da média, na qual aproximadamente 68% dos valores se encontram dentro de um desvio padrão da média, e 95% dentro de dois desvios padrão. Devido ao seu formato característico em forma de sino, ela também é conhecida como <em>bell curve</em>.</p>
<p>Para essa análise serão utilizados histogramas, que permitem observar visualmente o formato da distribuição dos dados e identificar possíveis assimetrias ou caudas mais longas em uma das extremidades. Além disso, utilizaremos Q-Q plots, que comparam os quantis observados nos dados com os quantis esperados de uma distribuição normal, permitindo avaliar visualmente o quanto cada variável se aproxima desse padrão.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop para gerar histogramas e Q-Q plots</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (var <span class="cf">in</span> <span class="fu">names</span>(vars_interesse)) {</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Histograma</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(vars_interesse, <span class="fu">aes_string</span>(<span class="at">x =</span> var)) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Histograma de"</span>, var),</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> var,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Densidade"</span>) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(p1)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Q-Q Plot</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  p2 <span class="ot">&lt;-</span> <span class="fu">ggqqplot</span>(vars_interesse,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>                 <span class="at">x =</span> var,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Q-Q Plot de"</span>, var),</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>                 <span class="at">xlab =</span> <span class="st">"Quantis Teóricos"</span>,</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>                 <span class="at">ylab =</span> <span class="st">"Quantis da Amostra"</span>)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(p2)</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite outside the scale range
(`stat_qq()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite outside the scale range
(`stat_qq_line()`).
Removed 10 rows containing non-finite outside the scale range
(`stat_qq_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_qq()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_qq_line()`).
Removed 2 rows containing non-finite outside the scale range
(`stat_qq_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing non-finite outside the scale range
(`stat_qq()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing non-finite outside the scale range
(`stat_qq_line()`).
Removed 4 rows containing non-finite outside the scale range
(`stat_qq_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-9.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_qq()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_qq_line()`).
Removed 2 rows containing non-finite outside the scale range
(`stat_qq_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-10.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-11.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite outside the scale range
(`stat_qq()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite outside the scale range
(`stat_qq_line()`).
Removed 10 rows containing non-finite outside the scale range
(`stat_qq_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-12.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-13.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_qq()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range (`stat_qq_line()`).
Removed 1 row containing non-finite outside the scale range (`stat_qq_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-14.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 17 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-15.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 17 rows containing non-finite outside the scale range
(`stat_qq()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 17 rows containing non-finite outside the scale range
(`stat_qq_line()`).
Removed 17 rows containing non-finite outside the scale range
(`stat_qq_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-16.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 13 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-17.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 13 rows containing non-finite outside the scale range
(`stat_qq()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 13 rows containing non-finite outside the scale range
(`stat_qq_line()`).
Removed 13 rows containing non-finite outside the scale range
(`stat_qq_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-4-18.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
</section>
<section id="análise-da-normalidade-das-variáveis" class="level2">
<h2 class="anchored" data-anchor-id="análise-da-normalidade-das-variáveis">Análise da Normalidade das Variáveis</h2>
<p>A normalidade das variáveis foi avaliada por meio da inspeção visual dos histogramas com curva de densidade e dos Q-Q plots. Os histogramas permitem observar o formato geral da distribuição dos dados, enquanto os Q-Q plots comparam os quantis observados com os quantis esperados de uma distribuição normal. Quando os pontos seguem aproximadamente a linha de referência no Q-Q plot, há evidência de comportamento próximo à normalidade; desvios sistemáticos indicam afastamentos dessa distribuição.</p>
<section id="life.expectancy" class="level3">
<h3 class="anchored" data-anchor-id="life.expectancy">Life.expectancy</h3>
<p>O histograma da variável Life.expectancy mostra maior concentração de valores na faixa entre aproximadamente 70 e 75 anos, com menor frequência de valores mais baixos. A distribuição é pouco simetrica, com uma calda maior à esquerda, indicando que poucos países possuem expectativa de vida significativamente menor que a maioria. No Q-Q plot, os pontos acompanham relativamente bem a linha de referência na região central, mas há desvios nas extremidades. Isso indica que a variável apresenta aproximação à normalidade no centro da distribuição, porém com desvios nas caudas.</p>
</section>
<section id="alcohol" class="level3">
<h3 class="anchored" data-anchor-id="alcohol">Alcohol</h3>
<p>A variável Alcohol apresenta também uma assimetria O histograma mostra maior concentração de observações em níveis mais baixos de consumo de álcool, indicando muitos países onde não há quase nenhum consumo, com alguns valores mais elevados formando uma cauda à direita. No Q-Q plot, novamente os pontos seguem a linha de referência na região central, mas apresentam desvios nos quantis inferiores e superiores.</p>
</section>
<section id="percentage.expenditure" class="level3">
<h3 class="anchored" data-anchor-id="percentage.expenditure">percentage.expenditure</h3>
<p>O histograma da variável percentage.expenditure revela até aqui a maior assimetria. A maior parte dos países apresenta valores relativamente baixos de gasto percentual, enquanto poucos países possuem valores extremamente elevados, produzindo uma longa cauda. O Q-Q plot confirma esse comportamento, com grande afastamento dos pontos da linha de referência nos quantis superiores. Essa variável apresenta clara violação da normalidade.</p>
</section>
<section id="bmi" class="level3">
<h3 class="anchored" data-anchor-id="bmi">BMI</h3>
<p>A variável BMI apresenta uma distribuição bimodal, com dois picos visíveis no histograma. Isso indica a presença de dois grupos distintos de países com níveis diferentes de índice de massa corporal médio, uns com índice por volta de 20 e outros por volta de 55. No Q-Q plot, observa-se que os pontos se afastam da linha de referência em várias regiões da distribuição, refletindo esse comportamento multimodal. Portanto, a variável não segue uma distribuição normal.</p>
</section>
<section id="total.expenditure" class="level3">
<h3 class="anchored" data-anchor-id="total.expenditure">Total.expenditure</h3>
<p>O histograma da variável Total.expenditure apresenta distribuição relativamente concentrada em torno de valores intermediários, com leve assimetria positiva. No Q-Q plot, os pontos seguem a linha de referência na região central, se mantendo dentro da faixa cinza exceto nos valores muito mais altos. Dessa forma, apenas os outliers extremos impedem que a variável seja considerada normal.</p>
</section>
<section id="gdp" class="level3">
<h3 class="anchored" data-anchor-id="gdp">GDP</h3>
<p>A variável GDP apresenta forte assimetria positiva, característica comum em indicadores econômicos globais. O histograma mostra grande concentração de países com valores mais baixos de PIB per capita e poucos países com valores muito elevados, gerando uma longa cauda à direita. No Q-Q plot, os pontos se afastam significativamente da linha de referência, especialmente nos quantis superiores, indicando claro desvio da normalidade.</p>
</section>
<section id="population" class="level3">
<h3 class="anchored" data-anchor-id="population">Population</h3>
<p>A variável Population apresenta assimetria positiva extrema, puxado por países super populosos como China e Índia. O histograma mostra que a maioria dos países possui populações relativamente menores, enquanto poucos países apresentam populações extremamente elevadas, produzindo uma cauda muito longa à direita. O Q-Q plot evidencia forte desvio da linha de referência em grande parte da distribuição, indicando que a variável está bastante distante de um comportamento normal.</p>
</section>
<section id="income.composition.of.resources" class="level3">
<h3 class="anchored" data-anchor-id="income.composition.of.resources">Income.composition.of.resources</h3>
<p>O histograma da variável Income.composition.of.resources apresenta distribuição relativamente concentrada em valores intermediários, com leve assimetria e dois picos. A maior parte das observações encontra-se em uma faixa relativamente estreita da escala. No Q-Q plot, os pontos seguem relativamente próximos da linha de referência na região central, com pequenos desvios nas extremidades. Isso indica uma distribuição relativamente equilibrada, ainda que não perfeitamente normal, com uma influência bimodal</p>
</section>
<section id="schooling" class="level3">
<h3 class="anchored" data-anchor-id="schooling">Schooling</h3>
<p>A variável Schooling apresenta um histograma com formato relativamente próximo ao de uma distribuição simétrica, com concentração maior de valores na região central. No Q-Q plot, os pontos acompanham razoavelmente bem a linha de referência na maior parte da distribuição, com pequenos desvios nas extremidades. Dessa forma, a variável apresenta comportamento relativamente próximo da normalidade quando comparada às demais variáveis analisadas.</p>
</section>
<section id="síntese-geral" class="level3">
<h3 class="anchored" data-anchor-id="síntese-geral">Síntese Geral</h3>
<p>De modo geral, observa-se que variáveis relacionadas à escala econômica ou tamanho dos países, como GDP, Population e percentage.expenditure, apresentam forte assimetria positiva, refletindo a desigualdade entre países onde alguns poucos países possuem números muito distantes da maioria. Já variáveis associadas a desenvolvimento humano, como Life.expectancy, Schooling e Income.composition.of.resources, apresentam distribuições mais equilibradas e próximas de um comportamento aproximadamente normz’al, ainda que com alguns desvios nas extremidades.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicando o teste de Shapiro-Wilk para as variáveis de interesse</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>shapiro_results <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (var <span class="cf">in</span> <span class="fu">names</span>(vars_interesse)) {</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove NAs antes de testar</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  data_for_test <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(vars_interesse[[var]])</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(data_for_test) <span class="sc">&gt;</span> <span class="dv">3</span> <span class="sc">&amp;&amp;</span> <span class="fu">length</span>(data_for_test) <span class="sc">&lt;=</span> <span class="dv">5000</span>) {</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>    shapiro_results[[var]] <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(data_for_test)</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (<span class="fu">length</span>(data_for_test) <span class="sc">&gt;</span> <span class="dv">5000</span>) {</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Amostra para o teste se o dataset for muito grande</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>    sample_data <span class="ot">&lt;-</span> <span class="fu">sample</span>(data_for_test, <span class="dv">5000</span>)</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>    shapiro_results[[var]] <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(sample_data)</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">warning</span>(<span class="fu">paste</span>(<span class="st">"Shapiro-Wilk aplicado a uma amostra de 5000 para"</span>, var, <span class="st">"devido ao tamanho do dataset."</span>))</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>    shapiro_results[[var]] <span class="ot">&lt;-</span> <span class="st">"Não foi possível aplicar Shapiro-Wilk (dados insuficientes ou muitos NAs)."</span></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibindo os resultados</span></span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>shapiro_results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Life.expectancy

    Shapiro-Wilk normality test

data:  data_for_test
W = 0.93706, p-value = 3.652e-07


$Alcohol

    Shapiro-Wilk normality test

data:  data_for_test
W = 0.90492, p-value = 1.011e-09


$percentage.expenditure

    Shapiro-Wilk normality test

data:  data_for_test
W = 0.52959, p-value &lt; 2.2e-16


$BMI

    Shapiro-Wilk normality test

data:  data_for_test
W = 0.93284, p-value = 1.143e-07


$Total.expenditure

    Shapiro-Wilk normality test

data:  data_for_test
W = 0.89019, p-value = 1.252e-10


$GDP

    Shapiro-Wilk normality test

data:  data_for_test
W = 0.67238, p-value &lt; 2.2e-16


$Population

    Shapiro-Wilk normality test

data:  data_for_test
W = 0.33353, p-value &lt; 2.2e-16


$Income.composition.of.resources

    Shapiro-Wilk normality test

data:  data_for_test
W = 0.96349, p-value = 0.0001467


$Schooling

    Shapiro-Wilk normality test

data:  data_for_test
W = 0.97259, p-value = 0.00129</code></pre>
</div>
</div>
</section>
<section id="teste-de-normalidade-shapiro-wilk" class="level3">
<h3 class="anchored" data-anchor-id="teste-de-normalidade-shapiro-wilk">Teste de Normalidade (Shapiro-Wilk)</h3>
<p>Para complementar a análise visual realizada por meio dos histogramas e Q-Q plots, foi aplicado o teste de Shapiro-Wilk para avaliar estatisticamente a normalidade das variáveis. Nesse teste, a hipótese nula (H₀) assume que os dados seguem uma distribuição normal. Assim, p-valores menores que 0,05 indicam rejeição da hipótese de normalidade.</p>
<p>Os resultados obtidos mostram que todas as variáveis apresentam p-valores inferiores a 0,05, indicando rejeição da hipótese de normalidade para todas elas.</p>
<p>Esse resultado confirma, em grande parte, as evidências observadas na análise gráfica. Variáveis como percentage.expenditure, GDP e Population apresentaram valores muito baixos do estatístico W e p-valores extremamente pequenos, reforçando a forte assimetria observada nos histogramas e Q-Q plots. Essas variáveis possuem distribuições altamente concentradas em valores menores, com caudas longas à direita, o que as afasta significativamente de uma distribuição normal.</p>
<p>Por outro lado, variáveis como Life.expectancy, BMI, Income.composition.of.resources e Schooling apresentaram valores do estatístico W mais próximos de 1, sugerindo distribuições relativamente mais próximas da normalidade. Ainda assim, os p-valores indicam que essas variáveis também não seguem perfeitamente uma distribuição normal, o que já era sugerido pelos pequenos desvios observados nas caudas dos Q-Q plots.</p>
<p>De modo geral, os resultados do teste de Shapiro-Wilk confirmam a análise visual realizada anteriormente, indicando que, embora algumas variáveis apresentem comportamento aproximadamente simétrico na região central da distribuição, nenhuma delas segue estritamente uma distribuição normal.</p>
</section>
</section>
</section>
<section id="qualidade-de-dados-completude-e-imputação" class="level1">
<h1>6. Qualidade de Dados: Completude e Imputação</h1>
<p>Antes de avançar para outras análises, é importante avaliar a qualidade dos dados, e um dos aspectos mais básicos disso é a completude.</p>
<p><strong>Em suas palavras, como é definido completude?</strong></p>
<p>Completude é o quão integros estão os dados de uma base, sem valores faltantes sejam por erros de medição ou processamento, de forma que cada linha do nosso dataset possua todas as variáveis devidamente indicadas em suas colunas, sem dados faltantes ou incoerentes (tipo diferente de dado)</p>
<p><strong>Qual o impacto em uma análise exploratória de dados?</strong></p>
<p>Dados incompletos podem afetar bastante uma análise exploratória de dados, pois nem sempre é possível identificar a natureza destes dados faltantes, ou o fenômeno que causou essas lacunas. Ou seja, caso os dados faltantes possuam algum tipo de viés, como erro em um equipamento de medição quando os dados são muito altos, é possível que nossa análise possua um viés.</p>
<p>Ademais, ainda que estes dados ocorram de forma aleatória, cada dado faltante é uma informação a menos que o nosso dataset possui, diminuindo portando a sua qualidade e aplicabilidade para analisar o fenômeno de interesse. Ao perdermos uma quantia como 20% dos dados por conta de dados faltantes, podemos deixar de obter insights valiosos na nossa análise.</p>
<p>Por fim, os modelos matemáticos estatísticos, gráficos e de machine learning por vezes não conseguem lidar com dados incompletos, de forma que é necessário etapas adicionais de processamento dos dados para viabilizar este tipo de análise, que perde um pouco da sua aplicabilidade</p>
<section id="completude-para-cada-variável" class="level2">
<h2 class="anchored" data-anchor-id="completude-para-cada-variável">Completude para cada Variável</h2>
<p>A seguir, vamos verificar o nível de completude de cada variável utilizada no dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculando a completude (%) para cada variável de interesse</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>completude <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(<span class="sc">!</span><span class="fu">is.na</span>(vars_interesse)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>completude_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variavel =</span> <span class="fu">names</span>(completude),</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Completude =</span> <span class="fu">round</span>(completude, <span class="dv">2</span>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibindo a tabela de completude</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(completude_df, <span class="at">caption =</span> <span class="st">"Completude das Variáveis de Interesse (%)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Completude das Variáveis de Interesse (%)</caption>
<colgroup>
<col style="width: 42%">
<col style="width: 42%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Variavel</th>
<th style="text-align: right;">Completude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Life.expectancy</td>
<td style="text-align: left;">Life.expectancy</td>
<td style="text-align: right;">94.82</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcohol</td>
<td style="text-align: left;">Alcohol</td>
<td style="text-align: right;">98.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">percentage.expenditure</td>
<td style="text-align: left;">percentage.expenditure</td>
<td style="text-align: right;">100.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">BMI</td>
<td style="text-align: left;">BMI</td>
<td style="text-align: right;">97.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total.expenditure</td>
<td style="text-align: left;">Total.expenditure</td>
<td style="text-align: right;">98.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">GDP</td>
<td style="text-align: left;">GDP</td>
<td style="text-align: right;">94.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Population</td>
<td style="text-align: left;">Population</td>
<td style="text-align: right;">99.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">Income.composition.of.resources</td>
<td style="text-align: left;">Income.composition.of.resources</td>
<td style="text-align: right;">91.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schooling</td>
<td style="text-align: left;">Schooling</td>
<td style="text-align: right;">93.26</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="imputação-de-dados-com-mice" class="level2">
<h2 class="anchored" data-anchor-id="imputação-de-dados-com-mice">Imputação de Dados com MICE</h2>
<p>Apesar do dataset apresentar uma boa completude nas variáveis analisadas, algumas delas ainda possuem uma pequena quantidade de valores faltantes. A maioria das variáveis apresenta mais de 94% de dados disponíveis, sendo que percentage.expenditure possui 100% de completude, enquanto Income.composition.of.resources apresenta o menor nível, com aproximadamente 91%. Embora a proporção de dados faltantes seja relativamente pequena, optamos por realizar a imputação para evitar a perda de observações nas etapas seguintes da análise.</p>
<p>Para realizar esse procedimento utilizaremos o pacote mice (Multivariate Imputation by Chained Equations). Esse método é frequentemente preferido à simples remoção de registros ou à substituição por média ou mediana, pois procura preservar a variabilidade dos dados e as relações entre as variáveis, gerando valores imputados de forma mais consistentes com a estrutura observada no conjunto de dados.</p>
<p>Durante a aplicação inicial do método utilizando todas as variáveis selecionadas, foi identificado um problema de singularidade computacional na matriz de predição. Esse problema ocorre quando algumas variáveis apresentam alta colinearidade, isto é, quando duas ou mais variáveis carregam praticamente a mesma informação estatística. No conjunto analisado, por exemplo, observamos correlações muito elevadas entre Schooling e Income.composition.of.resources, bem como entre GDP e percentage.expenditure, o que dificulta a estimação dos modelos internos utilizados pelo algoritmo de imputação.</p>
<p>Para contornar esse problema, foi realizada uma redução do conjunto de variáveis utilizadas no modelo de imputação, mantendo apenas um subconjunto representativo e menos redundante. A seleção final considerou tanto a relevância das variáveis para explicar a expectativa de vida quanto a redução da colinearidade entre elas, resultando nas variáveis Life.expectancy, BMI, GDP, Schooling e Alcohol. Esse conjunto permite capturar diferentes dimensões associadas à expectativa de vida, incluindo fatores socioeconômicos, educacionais, comportamentais e de saúde, ao mesmo tempo em que garante maior estabilidade para o processo de imputação.</p>
<p>Após esse ajuste, o método MICE foi aplicado utilizando o algoritmo Predictive Mean Matching (PMM) com cinco conjuntos imputados (m=5). O método PMM foi escolhido por preservar melhor a distribuição original dos dados, uma vez que os valores imputados são baseados em observações reais semelhantes, em vez de serem apenas estimativas geradas por modelos paramétricos.</p>
<p>O conjunto final de dados utilizado nas análises subsequentes foi obtido a partir do primeiro dataset completo gerado pelo procedimento de imputação.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecionando um subconjunto menor de variáveis para imputação</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>vars_mice <span class="ot">&lt;-</span> vars_interesse <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    Life.expectancy,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    Alcohol,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    BMI,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    GDP,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>    Schooling</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicando MICE com PMM</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>imputed_data <span class="ot">&lt;-</span> <span class="fu">mice</span>(</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  vars_mice,</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">m =</span> <span class="dv">5</span>,</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"pmm"</span>,</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">500</span>,</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">printFlag =</span> <span class="cn">FALSE</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtendo o primeiro conjunto imputado</span></span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a>vars_mice_imputed <span class="ot">&lt;-</span> <span class="fu">complete</span>(imputed_data, <span class="dv">1</span>)</span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificando se restaram NAs</span></span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(vars_mice_imputed))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizando o resultado</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vars_mice_imputed)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Life.expectancy   Alcohol      BMI       GDP Schooling
1        58.19375 0.0143750 15.51875  340.0154   8.21250
2        75.15625 4.8487500 49.06875 2119.7267  12.13750
3        73.61875 0.4066667 48.74375 2847.8534  12.71250
4        49.01875 5.7406667 18.01875 1975.1430   8.04375
5        75.05625 7.9493333 38.42500 9759.3057   8.84375
6        75.15625 7.9666667 54.98125 6998.5751  16.50625</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Criando a matriz de espalhamento para as variáveis de interesse</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  vars_mice_imputed,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Matriz de Espalhamento das Variáveis de Interesse"</span>,</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">0.1</span>,</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.5</span>),</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex.labels =</span> <span class="fl">0.8</span>,</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower.panel =</span> panel.smooth</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculando a matriz de correlação</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(vars_mice_imputed, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(cor_matrix, <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Life.expectancy Alcohol  BMI  GDP Schooling
Life.expectancy            1.00    0.43 0.64 0.59      0.76
Alcohol                    0.43    1.00 0.27 0.52      0.60
BMI                        0.64    0.27 1.00 0.35      0.50
GDP                        0.59    0.52 0.35 1.00      0.57
Schooling                  0.76    0.60 0.50 0.57      1.00</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizando a matriz de correlação com corrplot</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  cor_matrix,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"color"</span>,</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"upper"</span>,</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.col =</span> <span class="st">"black"</span>,</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.srt =</span> <span class="dv">45</span>,</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.cex =</span> <span class="fl">0.7</span>,</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">addCoef.col =</span> <span class="st">"black"</span>,</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">number.cex =</span> <span class="fl">0.5</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pd_analise_exploratoria_dados_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="análise-bivariada-testes-de-hipóteses" class="level1">
<h1>7. Análise Bivariada: Testes de Hipóteses</h1>
<p>Para validar as observações feitas na EDA, realizaremos três testes de hipóteses conforme as categorias solicitadas.</p>
<section id="teste-numérica-vs.-numérica-correlação-de-pearson" class="level3">
<h3 class="anchored" data-anchor-id="teste-numérica-vs.-numérica-correlação-de-pearson">Teste Numérica vs.&nbsp;Numérica: Correlação de Pearson</h3>
<p>Vamos testar se existe uma correlação estatisticamente significativa entre a schooling e a Expectativa de Vida.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de Correlação de Pearson</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># H0: Não há correlação linear entre as variáveis (cor = 0)</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H1: Há correlação linear significativa (cor != 0)</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  vars_mice_imputed<span class="sc">$</span>Life.expectancy,</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  vars_mice_imputed<span class="sc">$</span>Schooling,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"pearson"</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  vars_mice_imputed$Life.expectancy and vars_mice_imputed$Schooling
t = 16.18, df = 191, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.6936418 0.8141857
sample estimates:
      cor 
0.7603868 </code></pre>
</div>
</div>
<p>O teste de correlação de Pearson entre Life.expectancy e Schooling indica uma correlação positiva forte entre as duas variáveis (r = 0.76). O valor de p extremamente pequeno (p &lt; 2.2e-16) leva à rejeição da hipótese nula de ausência de correlação linear, indicando que a associação observada é estatisticamente significativa. O intervalo de confiança de 95% para a correlação (0.69 a 0.81) reforça que essa relação é consistentemente positiva. Em termos práticos, esse resultado sugere que países com maior nível médio de escolaridade tendem a apresentar maior expectativa de vida, indicando que fatores educacionais estão fortemente associados ao desenvolvimento humano e às condições de saúde da população.</p>
</section>
<section id="teste-numérica-vs.-categórica-2-classes-teste-t" class="level3">
<h3 class="anchored" data-anchor-id="teste-numérica-vs.-categórica-2-classes-teste-t">Teste Numérica vs.&nbsp;Categórica (2 classes): Teste T</h3>
<p>Vamos comparar a Expectativa de Vida entre países desenvolvidos e em desenvolvimento.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recriando um dataframe com Status + variáveis imputadas</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>df_imputed <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Status) <span class="sc">%&gt;%</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(vars_mice_imputed)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Garantindo que Status seja um fator</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>df_imputed<span class="sc">$</span>Status <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df_imputed<span class="sc">$</span>Status)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste t de Student para amostras independentes</span></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a><span class="co"># H0: As médias de expectativa de vida são iguais entre os grupos</span></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a><span class="co"># H1: As médias são diferentes</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Life.expectancy <span class="sc">~</span> Status, <span class="at">data =</span> df_imputed)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Life.expectancy by Status
t = 13.341, df = 129.93, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group Developed and group Developing is not equal to 0
95 percent confidence interval:
 10.04783 13.54686
sample estimates:
 mean in group Developed mean in group Developing 
                79.19785                 67.40050 </code></pre>
</div>
</div>
<p>O teste t de Welch foi aplicado para comparar a expectativa de vida média entre países classificados como Developed e Developing. Os resultados mostram uma diferença estatisticamente significativa entre os grupos (t = 13.34, p &lt; 2.2e-16). A média de expectativa de vida nos países desenvolvidos é aproximadamente 79.2 anos, enquanto nos países em desenvolvimento é cerca de 67.4 anos. O intervalo de confiança de 95% para a diferença entre as médias (aproximadamente 10.05 a 13.55 anos) indica que a diferença é substancial. Esse resultado evidencia um gap significativo de expectativa de vida entre os dois grupos, refletindo diferenças estruturais relacionadas a renda, acesso a serviços de saúde, educação e condições gerais de vida.</p>
</section>
<section id="teste-numérica-vs.-categórica-mais-de-2-classes-anova" class="level3">
<h3 class="anchored" data-anchor-id="teste-numérica-vs.-categórica-mais-de-2-classes-anova">Teste Numérica vs.&nbsp;Categórica (mais de 2 classes): ANOVA</h3>
<p>Para testar mais de duas classes, como não há variável categórica deste tipo no nosso dataset, vamos categorizar o GDP em tercis (Baixo, Médio e Alto) e ver se a Expectativa de Vida varia entre eles.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Criando variável categórica de PIB com 3 níveis</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>vars_mice_imputed <span class="ot">&lt;-</span> vars_mice_imputed <span class="sc">%&gt;%</span> </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">GDP_Group =</span> <span class="fu">cut</span>(</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>      GDP,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">breaks =</span> <span class="fu">quantile</span>(GDP, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>, <span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>, <span class="dv">1</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Baixo"</span>, <span class="st">"Médio"</span>, <span class="st">"Alto"</span>),</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">include.lowest =</span> <span class="cn">TRUE</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA de um fator</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a><span class="co"># H0: As médias de expectativa de vida são iguais nos três níveis de PIB</span></span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a><span class="co"># H1: Pelo menos uma média é diferente</span></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>res_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Life.expectancy <span class="sc">~</span> GDP_Group, <span class="at">data =</span> vars_mice_imputed)</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
GDP_Group     2   8975    4487   124.6 &lt;2e-16 ***
Residuals   190   6845      36                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A análise de variância (ANOVA) foi utilizada para avaliar se a expectativa de vida difere entre três grupos de países definidos pelo nível de PIB (Baixo, Médio e Alto). O teste apresentou resultado altamente significativo (F = 124.6, p &lt; 2e-16), indicando rejeição da hipótese nula de igualdade entre as médias. Isso significa que pelo menos um dos grupos de PIB possui expectativa de vida média diferente dos demais. O valor elevado do estatístico F sugere que a variação entre os grupos de PIB é muito maior do que a variação interna dentro de cada grupo. Esse resultado reforça a ideia de que fatores econômicos agregados, como o nível de riqueza dos países, estão fortemente associados às diferenças observadas na expectativa de vida.</p>
</section>
</section>
<section id="links" class="level1">
<h1>8. Links</h1>
<p>Foi desenvolvido um dashboard interativo em Shiny para complementar a análise exploratória apresentada no relatório. O aplicativo permite selecionar uma variável dentre as que foram imputadas pelo mice, e visualizar sua relação com a expectativa de vida por meio de um gráfico de dispersão, além de exibir a correlação de Pearson correspondente.</p>
<ul>
<li><p><strong>App Shiny:</strong> <a href="https://alan-alonso.shinyapps.io/pd-estatstica/">ShinyApps.io</a></p></li>
<li><p><strong>Código Fonte:</strong> <a href="https://github.com/AlansAlonso/PD-analise-exploratoria#">GitHub Repository</a></p></li>
<li><p><strong>Relatório Online:</strong> <a href="https://rpubs.com/Alan_Alonso/PD-Analise-Exploratoria">RPubs</a></p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>